### ISSUE TITLE
May I ask where you used the API_ KEY, I don't see API_ KEY used in the code

### ISSUE THREAD

**Issue by kkmoonlike** [Phaneendra97/SpeechRecognition-GoogleCloud#2]
![image](https://github.com/Phaneendra97/SpeechRecognition-GoogleCloud/assets/15172263/31f410f3-fc8d-4a1e-ac6b-367846f18caa)

**Comment by Phaneendra97** [comment]
I am sorry I don't quite remember what I tried to do updating the API, I've now rolled back to the previous API to make it look whole. here is the rollbacked changes https://github.com/Phaneendra97/SpeechRecognition-GoogleCloud/blob/master/app/src/main/java/com/example/sk/exp/MainActivity.java

Fair warning: This is 6 years old code and GCP has changed a lot with their API call. please refer the latest documentation.
